### ISSUE TITLE
How to fix this backend company-tabnine error?

### ISSUE THREAD

**Issue by Iorest** [TommyX12/company-tabnine#1]
Company: backend company-tabnine error "Symbol’s function definition is void: comp" with args (prefix)

**Comment by TommyX12** [comment]
Already fixed, please update on next release :)

**Comment by Iorest** [comment]
I'm glad  to get your quick reply, but it doesn't seem to work for me. Is there anything that needs attention
?
I'm use ubuntu18.10 and emacs 26.1.
and the message is
"TabNine server started.
Company: An error occurred in auto-begin
Company: backend company-tabnine error "Symbol’s function definition is void: comp" with args (prefix)
user-error: Cannot complete at point"

**Comment by TommyX12** [comment]
It's because I fixed it but melpa didn't build the next release yet. Wait
for that to happen (should be in a few hours) and update.

**Comment by TommyX12** [comment]
The fix is in the latest build. Please update :)

**Comment by Iorest** [comment]
OK，ths！
