### ISSUE TITLE
'TabNine::version' not working on Spacemacs

### ISSUE THREAD

**Issue by saneef** [TommyX12/company-tabnine#11]
I'm using Spacemacs. And tried to configure based on the instruction on the readme. TabNine seems working for me. See the screenshot below:

<img width="660" alt="screenshot 2019-01-11 at 10 02 42 am" src="https://user-images.githubusercontent.com/81863/51013415-44789700-1588-11e9-89cf-a032a173d8a0.png">

But, the problem is I'm not able to get any response from `TabNine::version` or `TabNine::active`. See the below screenshot:

<img width="660" alt="screenshot 2019-01-11 at 9 59 55 am" src="https://user-images.githubusercontent.com/81863/51013442-72f67200-1588-11e9-8822-dfa79be8b7db.png">

**Comment by TommyX12** [comment]
Which version of `company-tabnine` are you using? I recall fixing a small bug related to this, can you try if updating the package helps? Thanks.

**Comment by saneef** [comment]
I was facing problem with Spacemacs with vim controls (evil) set up, which was only a day old. So I hope the version was latest. Just before your reply I reinstalled the Spacemacs with emacs controls and reinstalled `company-mode` and `company-tabnine`. It worked like charm.

Not sure if the problem was with evil mode or my configurations. Anyways, I'm closing this issue. Thanks @TommyX12  for looking into it.

**Comment by saneef** [comment]
A note, the problem was with all Tabnine commands: `TabNine::version`, `TabNine::active`, `TabNine::sem`, etc.

**Comment by larebsyed** [comment]
@saneef Were you able to get it working with spacemacs evil mode, if not then this issue should be reopened. 
As I am facing a similar issue.
