### ISSUE TITLE
install-binary creates ~/TabNine even when binaries-folder is set elsewere

### ISSUE THREAD

**Issue by christopher-dG** [TommyX12/company-tabnine#12]
Using `company-tabnine` with `use-package`:

```el
(use-package company-tabnine
  :ensure t
  :custom company-tabnine-binaries-folder "~/.emacs.d/tabnine")
```

Running `company-tabnine-install-binary` results in an empty `~/TabNine` directory and a `~/.emacs.d/tabnine` that contains the binaries.

**Comment by christopher-dG** [comment]
Looks like this is the culprit:
https://github.com/TommyX12/company-tabnine/blob/2d63df791027ec2bcc8956be6b7078d17f95217c/company-tabnine.el#L465
Along with this constant: https://github.com/TommyX12/company-tabnine/blob/2d63df791027ec2bcc8956be6b7078d17f95217c/company-tabnine.el#L92

**Comment by TommyX12** [comment]
Should be fixed in the latest commit.
