### ISSUE TITLE
Cannot fallback to other backends when no candidates return from tab9 server

### ISSUE THREAD

**Issue by cireu** [TommyX12/company-tabnine#17]
# Info 
Emacs Ver: 27.0.5
company ver: https://github.com/company-mode/company-mode/commit/ad6ff0eecca99dc5ac8b6a8a6174df7d2ad88ae7
company-tabnine ver:  https://github.com/TommyX12/company-tabnine/commit/eedb8be8c0fbae4094d6452b999334c1bf009583

# Recipes

1. Load `dash` `s` `company` `unicode-escape` `names` and `company-tabnine`
2. Add `company-tabnine` to `company-backends` and turn on company-mode
3. Type `(let ((a (geth` in scratch buffer

Expect capf backend to complete `gethash` but tabnine backend keep the control and return 
no candidates.

**Comment by yuanzhhh** [comment]
mark

**Comment by TommyX12** [comment]
Fixed in the latest commit.
