### ISSUE TITLE
Enable downloading static Linux binary

### ISSUE THREAD

**Issue by alinnow** [TommyX12/company-tabnine#18]
Following up to https://github.com/zxqfl/TabNine/issues/36#issuecomment-513284271 (summary: a statically-linked binary is now available for systems where dynamic linking is unavailable or the standard library is in the standard include path, e.g. NixOS).

It should be possible to install and use this new binary. I'm happy to submit a PR for this, the only question is whether there should be some auto-detection (which would only detect NixOS until someone else runs into the issue) or to add a config option that would need to be set before calling `company-tabnine-install-binary`.

**Comment by TommyX12** [comment]
How about both? Add a config option that detect NixOS by default and if someone else run into it they can modify the option.
