### ISSUE TITLE
Error running timer ‘company-echo-show’

### ISSUE THREAD

**Issue by ghost** [TommyX12/company-tabnine#2]
**Error running timer ‘company-echo-show’: (error "Company: backend company-tabnine error \"Invalid function: (messages (alist-get 'promotional_message company-tabnine--result))\" with args (meta Singleton)")**

*My configuration:*
```emacs-lisp
(use-package company
        :demand
        :ensure t
        :hook ((after-init . global-company-mode))
        :config
        ;; Trigger completion immediately.
        (setq company-idle-delay 0)

        ;; Number the candidates (use M-1, M-2 etc to select completions).
        (setq company-show-numbers t)

        ;; Use the tab-and-go frontend.
        ;; Allows TAB to select and complete at the same time.
        (company-tng-configure-default)
        (setq company-frontends
              '(company-tng-frontend
                company-pseudo-tooltip-frontend
                company-echo-metadata-frontend)))

(use-package company-tabnine
        :ensure t
        :config
        (add-to-list 'company-backends #'company-tabnine))
```

*Screenshot:*

![skarmavbild 2018-11-13 kl 10 52 32](https://user-images.githubusercontent.com/924848/48405652-f6cfe180-e732-11e8-9339-94665e77cc66.png)

**Comment by TommyX12** [comment]
What's your emacs version and system configuration?

**Comment by ghost** [comment]
I'm running bleeding edge:
GNU Emacs 27.0.50 (build 2, x86_64-apple-darwin18.2.0, NS appkit-1671.10 Version 10.14.1 (Build 18B75)) of 2018-11-09

What parts of my configuration are you interested in? I have a huge init file but it doesn't cause any warnings and all settings are compartmentalized with use-package

**Comment by TommyX12** [comment]
It appears the problematic code is this:
```emacs
when-let ((messages (alist-get 'promotional_message company-tabnine--result)))
  (s-join " " messages)
```
And apparently in your version of emacs `((messages ...))` is being treated as a function call, with `(messages ...)` being the function. As of Emacs 26.1, `when-let` should work the same way as `let`. This is quite strange.

**Comment by ghost** [comment]
I wasn't able to reproduce this issue on my other machine running `GNU Emacs 27.0.50 (build 1, x86_64-apple-darwin18.0.0, NS appkit-1671.00 Version 10.14 (Build 18A391)) of 2018-11-11` with the same configuration. If I can't reproduce it on my first machine I'll close this

**Comment by ghost** [comment]
I get error every time on my first machine, now with `GNU Emacs 27.0.50 (build 3, x86_64-apple-darwin18.2.0, NS appkit-1671.10 Version 10.14.1 (Build 18B75)) of 2018-11-14` and latest version of all plugins, I'll see if I make a fix for it

**Comment by ghost** [comment]
Can't reproduce issue in latest version so I'm closing this
