### ISSUE TITLE
Treat periods as part of a word in nix-mode

### ISSUE THREAD

**Issue by LemonBreezes** [TommyX12/company-tabnine#20]
Even after running
(modify-syntax-entry ?. “w” nix-mode-syntax-table),
if I type “msmtp” and get completion options like “msmtp.enable = true;” but then enter a period, the completion pop-up closes. Instead, I would have liked to filter to options of the form “msmtp.*”

**Comment by TommyX12** [comment]
That's probably caused by TabNine uses its own logic for determining what a prefix is, and does not use Emacs's syntax table. You can file an issue here: https://github.com/zxqfl/TabNine to make TabNine itself parse prefix differently.

**Comment by LemonBreezes** [comment]
Thank you @TommyX12. I have just posted this issue there instead.
