### ISSUE TITLE
Emacs package-install says "No match"

### ISSUE THREAD

**Issue by martinthurn** [TommyX12/company-tabnine#22]
I'm following the README installation instructions "M-x package-install RET company-tabnine RET" but it just says "No match".  Is there some repository I need to add?  I'm using
GNU Emacs 25.2.2 (x86_64-pc-linux-gnu, GTK+ Version 3.22.21)

**Comment by martinthurn** [comment]
I figured it out.  I had to add the MELPA "bleeding edge" repository (I was only using the stable).  You might want to add a note about that in the instructions.  Thank you

**Comment by TommyX12** [comment]
Added. Thanks!
