### ISSUE TITLE
https://github.com/TommyX12/company-tabnine#known-issues Didn't work

### ISSUE THREAD

**Issue by carlos-wong** [TommyX12/company-tabnine#24]
I am added the config and restart emacs. But the candicates still not sort by the TabNine possible value.

**Comment by TommyX12** [comment]
Have you looked at the known issues section in the README? Also, what exactly is the config you used?

**Comment by carlos-wong** [comment]
I am used

```
;; workaround for company-transformers
(setq company-tabnine--disable-next-transform nil)
(defun my-company--transform-candidates (func &rest args)
(if (not company-tabnine--disable-next-transform)
    (apply func args)
    (setq company-tabnine--disable-next-transform nil)
    (car args)))

(defun my-company-tabnine (func &rest args)
(when (eq (car args) 'candidates)
    (setq company-tabnine--disable-next-transform t))
(apply func args))

(advice-add #'company--transform-candidates :around #'my-company--transform-candidates)
(advice-add #'company-tabnine :around #'my-company-tabnine)
```

from the know issue section. I thought the config is make the candicates sort by the TabNine possible  value?

**Comment by TommyX12** [comment]
TabNine will work out of the box.
This workaround is only for compatibility with the use of `company-transformers`. For example, `company-flx` modifies `company-transformers`. Don't use this if you do not have `company-flx` installed, or if you don't use `company-transformers`.

这个补丁是为了兼容 `company-transformers` 。如果你没有修改 `company-transformers` 且没有安装诸如 `company-flx` 之类的会修改 `company-transformers` 的plugin，不要使用这段config.
