### ISSUE TITLE
Allow to switch TabNine version

### ISSUE THREAD

**Issue by cldotdev** [TommyX12/company-tabnine#26]
Since [some issues](https://github.com/zxqfl/TabNine/issues/43) exist on the latest TabNine version, I want to switch the TabNine version to the older. Is there a way to do that?

**Comment by superDuperCyberTechno** [comment]
I guess you could hardcode it into the fetcher script. I'm not sure and it's definitely not a very solid solution. What client are you using?

**Comment by cldotdev** [comment]
I work on small instance of cloud server (with 2-4 GB memory). TabNine eats 1.5 GB at initial, and I am not sure if it is normal. How to modify the fetcher script so it can download the old TabNine version?

**Comment by TommyX12** [comment]
> I work on small instance of cloud server (with 2-4 GB memory). TabNine eats 1.5 GB at initial, and I am not sure if it is normal. How to modify the fetcher script so it can download the old TabNine version?

TabNine does eat a lot of memory. It might also be because local deep-tabnine is enabled. You can check by typing `TabNine::config` in any buffer (your browser should then automatically open to TabNine's config page) and disable Deep TabNine Local (you will lose deep learning completion).

**Comment by superDuperCyberTechno** [comment]
> I work on small instance of cloud server (with 2-4 GB memory). TabNine eats 1.5 GB at initial, and I am not sure if it is normal. How to modify the fetcher script so it can download the old TabNine version?

What editor do you use?

**Comment by cldotdev** [comment]
@superDuperCyberTechno I use Emacs 26.3
@TommyX12 I set local_enabled to No in TabNine config, and it resolves my question. Thanks!

**Comment by pweibert** [comment]
> l
Sorry but how do I open tabnine configuration page? Typing `TabNine::config`  doesn't open anything on my side . (GNU Emacs 27.1)

**Comment by pweibert** [comment]
> @superDuperCyberTechno I use Emacs 26.3 @TommyX12 I set local_enabled to No in TabNine config, and it resolves my question. Thanks!

Sorry, but how can I open the configuration page? typing in `TabNine::config`  doesn't open anything on my side. (GNU Emacs 27.1)

**Comment by cldotdev** [comment]
> > @superDuperCyberTechno I use Emacs 26.3 @TommyX12 I set local_enabled to No in TabNine config, and it resolves my question. Thanks!
> 
> Sorry, but how can I open the configuration page? typing in `TabNine::config` doesn't open anything on my side. (GNU Emacs 27.1)

![圖片](https://user-images.githubusercontent.com/2265716/212359497-a8afe51b-fe42-490d-ac12-33e688624e2c.png)

If the completion does not work, you can try to type `M-x company-tabnine` manually.
The URL may have changed in the latest version of Tabnine binary.

**Comment by pweibert** [comment]
Thanks! `M-x company-tabnine` solved it.
