### ISSUE TITLE
Freezes during completion

### ISSUE THREAD

**Issue by Donaim** [TommyX12/company-tabnine#29]
If company-tabnine enabled, emacs frequently freezes when I type, even on small projects.

I think that reason is that completion is not asynchronous.
If so, please make it asynchonous, because processing completions takes a lot of time, so freezes are very annoying.

Emacs verison 25.2.2
company config
```
(use-package company
             :ensure t
             :config
             (setq company-minimum-prefix-length 1)
             (setq company-idle-delay 0))
```

**Comment by carlos-wong** [comment]
I am have the same issue. It looks like the TabNine is overuse the CPU. On my macbook pro ,the cpu cost is 700%。 Dose change the company-idle-delay will help?

**Comment by carlos-wong** [comment]
@TommyX12

**Comment by TommyX12** [comment]
One possible reason is that TabNine may enable local deep learning completion by default, which is very CPU-intensive if your computer can't handle it. See https://github.com/TommyX12/company-tabnine/issues/26#issuecomment-538055948 for how to disable.

**Comment by carlos-wong** [comment]
Thanks. I will test the config.
