### ISSUE TITLE
'Cannot complete at point' every time when 'M-x company-tabnine' is run

### ISSUE THREAD

**Issue by xeniagda** [TommyX12/company-tabnine#32]
After following the instructions in the README-file, doing `M-x company-tabnine` does not bring up a completion, but instead shows the message `Cannot complete at point` in the minibuffer.

It seems like the client is communicating with the server, as typing `TabNine::config` brings up the configuration page in the browser, `TabNine::sem` shows the `Semantic completion enabled.` message and so on.

The `TabNine server started.`-message is the only other one to show up in the `Messages`-buffer after starting `company-tabnine`.

I am quite lost and nothing I try to do to fix this seems to work. If there are any details you would need to resolve this, I am happy to send them.

Thank you

**Comment by TommyX12** [comment]
`company-tabnine` is a **backend** for `company-mode`. You do not need to run `M-x company-tabnine`, since that's the backend function, not one that should be called with `M-x`. Please see https://company-mode.github.io/ for instructions on how to use `company-mode`.
