### ISSUE TITLE
[Question]  company-tabnine-always-trigger

### ISSUE THREAD

**Issue by therobotreader** [TommyX12/company-tabnine#33]
I'm curious what the rationale behind adding this behavior was.  It makes things like using pdb(lots of one-letter commands) very difficult, because I have to cancel the completion for everything.

**Comment by jas0nt** [comment]
I have the same question, is there any way to trigger tabnine **only** in prog-mode?

**Comment by TommyX12** [comment]
The `company-tabnine-always-trigger` option is to make TabNine trigger even when company doesn't (by default), such as when pressing space. TabNine is able to complete multiple words (even entire line), and meaningful candidates can pop-up even when space, comma, or other characters are pressed.

To have mode-local behavior, such as changing this option in a certain mode, or disable completion entirely, just use a hook, such as:

```emacs
(add-hook 'some-mode-hook (lambda () (setq-local company-tabnine-always-trigger nil)))
```
