### ISSUE TITLE
Adding --client flag when running the binary

### ISSUE THREAD

**Issue by boaz-codota** [TommyX12/company-tabnine#38]
Thanks for building and maintaining this plugin! 

You are awesome and we appreciate your help in making TabNine approachable to Emacs users 🙌🏻🙌🏻

As I have no ability in reading/writing lisp, could you please add a flag to the binary when it is being ran? The flag is `--client` and its value should be `emacs`. This enables us to better understand our users and make sure we are not breaking any ability to any of them.

This is roughly the line that need to change (from what I was able to interpret from my zero lisp knowledge):
https://github.com/TommyX12/company-tabnine/blob/master/company-tabnine.el#L349

Thanks!!

**Comment by TommyX12** [comment]
No problem!
I have added the flag in the latest commit. It was indeed the line that needed to change; quite impressive you can figure it out without knowledge of lisp :D
