### ISSUE TITLE
company-tabnine-install-binary: Symbol’s function definition is void: string-trim

### ISSUE THREAD

**Issue by grantjenks** [TommyX12/company-tabnine#4]
Just installed from MELPA. Ran M-x company-tabnine-install-binary

```
Getting current version...
Contacting host: update.tabnine.com:443
Wrote /Users/grantj/TabNine/version
company-tabnine-install-binary: Symbol’s function definition is void: string-trim
```

Emacs version 26.1. Wish I could provide more info. How do I debug?

**Comment by TommyX12** [comment]
Should be fixed in the next build.

**Comment by grantjenks** [comment]
Awesome! Thanks.

Is that available soon? How do I track the next build in MELPA?

**Comment by TommyX12** [comment]
It should be on https://melpa.org :)

**Comment by TommyX12** [comment]
Fix is in the latest build. Let me know if it's fixed 😛

**Comment by grantjenks** [comment]
It works! Thank you.
