### ISSUE TITLE
Error when trying to install tabnine binary on Apple M1

### ISSUE THREAD

**Issue by xqliu** [TommyX12/company-tabnine#41]
## Description

When trying to install tabnine binary via `company-tabnine-install-binary`, the log shows

```
Installing at ~/.TabNine/3.2.28/i686-apple-darwin/TabNine. Downloading https://update.tabnine.com/3.2.28/i686-apple-darwin/TabNine ...
Wrote /Users/xqianliu/.TabNine/3.2.28/i686-apple-darwin/TabNine
TabNine installation complete.
```

But when I check content of file TabNine, it shows 
```
<html>
<head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>403 Forbidden</title></head>
<body>
<h1>403 Forbidden</h1>
<ul>
<li>Code: AccessDenied</li>
<li>Message: Access Denied</li>
<li>RequestId: 5CFD4148C692BBAA</li>
<li>HostId: ZzelKDLGX9jtSqMMbP1c4qcpIwp15Xi9jeNdHoGwDp45Ugj8cwx/Y+Kpxyf3aAk4E8gXkqvUVJg=</li>
</ul>
<h3>An Error Occurred While Attempting to Retrieve a Custom Error Document</h3>
<ul>
<li>Code: AccessDenied</li>
<li>Message: Access Denied</li>
</ul>
<hr/>
</body>
</html>
```

Operation system: Apple M1 11.01

Seems i686 was returned as arch here

**Comment by xqliu** [comment]
Just post my temp solution in case it might help anyone who also meet this issue

I have workaround this issue by install the tabNine plugin for jetbrains idea(it will download the TabNine executable file to `~/.TabNine/3.2.63/x86_64-apple-darwin`, and then copy the file to a folder named  `~/.TabNine/3.2.63/i686-apple-darwin` folder.

**Comment by TommyX12** [comment]
This should be fixed as of the latest version. Let me know if the issue persists.

**Comment by xqliu** [comment]
Hi, thanks for the fix, 

currently when I invoke company-tabnine, it shows "Unknown or unsupport architecture arm"

I have try to invoke `company-tabnine--get-target` manually and it also returns 

"Unknown or unsupport architecture arm"

I tried to see output of variable `system-configuration` and on my machine it returns `arm-apple-darwin20.1.0`, but seems there's no such match logic inside the `company-tabnine--get-target` function.

![image](https://user-images.githubusercontent.com/22554/108592644-d67b3c80-73a9-11eb-9139-f0f0019062e5.png)


I will try to raise a PR if I manage to resolve the issue.

Thanks.

**Comment by xqliu** [comment]
After applied the linked patch seems both  `company-tabnine-install-binary` and `company-tabnine` both works.
