### ISSUE TITLE
Tries to untar a zipfile when downloading the binary

### ISSUE THREAD

**Issue by pcn** [TommyX12/company-tabnine#49]
Just trying this out, and I got this in the `*Messages*` buffer:

```
Installing at ~/.TabNine/3.3.96/x86_64-unknown-linux-gnu/TabNine. Downloading https://update.tabnine.com/bundles/3.3.96/x86_64-unknown-linux-gnu/TabNine.zip ...
Wrote /home/spacey/.TabNine/3.3.96/x86_64-unknown-linux-gnu.zip
tar: This does not look like a tar archive
tar: Skipping to next header
tar: Exiting with failure status due to previous errors
```

**Comment by TommyX12** [comment]
Should be fixed in next build; just changed it to use `tar` on Windows only.

**Comment by pcn** [comment]
@TommyX12 I think that's not going to work. This change:
https://github.com/TommyX12/company-tabnine/blob/master/company-tabnine.el#L656-L662 is still going to fail on linux (I don't know about macos) because tar won't read and extract from a zip archive.

**Comment by TommyX12** [comment]
Thank you for catching that. My stupid brain swapped the then and else clause by accident. Fixed now.
