### ISSUE TITLE
Server does not start reliably on NixOS

### ISSUE THREAD

**Issue by matthew-piziak** [TommyX12/company-tabnine#5]
Executable installation happens without any visible error, but once completion is requested, TabNine breaks.
```
Company: An error occurred in auto-begin
Company: backend company-tabnine error "Process company-tabnine--process not running" with args (prefix)
user-error: Cannot complete at point
TabNine server started.
json-read: JSON readtable error: 47
```

**Comment by matthew-piziak** [comment]
Also this?

```
~/TabNine/1.0.7/x86_64-unknown-linux-gnu $ chmod +x TabNine
~/TabNine/1.0.7/x86_64-unknown-linux-gnu $ ./TabNine
~/TabNine/1.0.7/x86_64-unknown-linux-gnu $
```

Nothing. How is the binary supposed to work?

**Comment by matthew-piziak** [comment]
Any way I can help provide more information about this problem?

**Comment by TommyX12** [comment]
Can you provide your system configuration as well as emacs version?
Thanks.

**Comment by matthew-piziak** [comment]
Certainly.

```
 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.87, NixOS, 18.03.133389.b551f89e256 (Impala)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.0.4`
 - channels(matt): `"nixos-18.03.133236.8edf566ee40, unstable-19.03pre152634.218ce4de508"`
 - channels(root): `"nixos-18.03.133389.b551f89e256, unstable-19.03pre162390.86344b3a52b"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixpkgs`
```

```
GNU Emacs 26.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.1) of 2018-12-11
```

**Comment by TommyX12** [comment]
> Also this?
> 
> ```
> ~/TabNine/1.0.7/x86_64-unknown-linux-gnu $ chmod +x TabNine
> ~/TabNine/1.0.7/x86_64-unknown-linux-gnu $ ./TabNine
> ~/TabNine/1.0.7/x86_64-unknown-linux-gnu $
> ```
> Nothing. How is the binary supposed to work?

This seems like a TabNine problem (process terminates immediately). Would you mind posting an issue here?: https://github.com/zxqfl/tabnine

**Comment by matthew-piziak** [comment]
Closing in favor of https://github.com/zxqfl/TabNine/issues/36
