### ISSUE TITLE
Fix broken 404 https://tabnine.com/blog/deep link in README 

### ISSUE THREAD

**Issue by Dima-369** [TommyX12/company-tabnine#57]
https://tabnine.com/blog/deep now 404s.

Not quite sure which the correct link is though.

**Comment by karta0807913** [comment]
I think now it's here [https://www.tabnine.com/blog/](https://www.tabnine.com/blog/).

**Comment by tillydray** [comment]
I searched their blog for "deep" and found "deep model" so then I searched for "deep model" and this is the only result I got https://www.tabnine.com/blog/tabnine-memory-and-cpu-usage/. So I'm guessing that's the specific info that the repo author was trying to link to

**Comment by TommyX12** [comment]
Thanks, changed the readme.
