### ISSUE TITLE
Tabnine not working with lsp.

### ISSUE THREAD

**Issue by vitalytiru** [TommyX12/company-tabnine#59]
Is it possible to make it work together with rust lsp?

**Comment by karta0807913** [comment]
Hello @lastgosumatt, you can install the lsp server by following the instruction in [Tabnine website](https://www.tabnine.com/semantic) or you can use my [script](https://github.com/karta0807913/emacs.d/blob/master/lisp/init-tabnine-capf.el) to combine the `lsp-mode` and `company-tabnine`

**Comment by karta0807913** [comment]
By the way, the command `Tabnine::sem` just simply insert into the emacs editor (when you activate the `company-tabnine`).

**Comment by vitalytiru** [comment]
> Hello @lastgosumatt, you can install the lsp server by following the instruction in [Tabnine website](https://www.tabnine.com/semantic) or you can use my [script](https://github.com/karta0807913/emacs.d/blob/master/lisp/init-tabnine-capf.el) to combine the `lsp-mode` and `company-tabnine`

Thank you! I try this one :)
