### ISSUE TITLE
Semantic Completion

### ISSUE THREAD

**Issue by sethdusek** [TommyX12/company-tabnine#8]
[TabNine now has Semantic Completion](https://tabnine.com/semantic) but I'm not quite sure how to enable this using this package. It seems to require typing 'TabNine::sem' inside the editor to enable it. Perhaps a command like company-tabnine-semantic-completion should be added?

**Comment by TommyX12** [comment]
I have fixed a bug that makes the client unable to launch the latest version (please wait for the next melpa build then update this package). Currently typing `TabNine::sem` is the only way to enable semantic completion, so if that doesn't work then the above bug might be the issue.

**Comment by sethdusek** [comment]
Ah, thanks! I guess I should close this issue now.
